#!/usr/bin/env bash

# themes
apm install fonts
apm install atom-material-ui
apm install atom-material-syntax
apm install seti-ui
apm install seti-syntax
apm install monokai-seti
apm install seti-icons
apm install file-icons

# common
apm install git-plus
apm install git-time-machine
apm install terminal-plus
apm install minimap
apm install markdown-preview-plus
apm install split-diff
apm install environment
apm install minimap-git-diff
apm install git-control
apm install git-blame
apm install atom-fuzzy-grep #requires ag command

# js development
apm install react
apm install linter-eslint
apm install autocomplete-modules
apm install language-jade

# shells
apm install language-fish-shell

# docker
apm install language-docker
apm install linter-docker

# clojure
apm install proto-repl
